### ISSUE TITLE
is this theme abandoned

### ISSUE THREAD

**Issue by fasteddys** [2sic/oqtane-theme-2shine-bs5#5]

**Comment by iJungleboy** [comment]
Good question, but actually no ;)

We haven't been able to document it yet - which we really should, because the theme does so much in can be daunting to start with it...

But maintenance has been slow, as Oqtane 5 has various major changes with SSR etc. and isn't quite stable yet, so we're pushing this back (and our resources have been quite absorbed by work around that as well).

**Comment by enfJoao** [comment]
Please don't let this project die.
2shine for DNN works wonders. Would love to see it work with Oqtane, since there are no actual decent themes for it.

**Comment by iJungleboy** [comment]
@enfJoao actually we're in the middle of creating a brand new system.

Been working on it day and night for the last 8 weeks.

So really commited ;)

**Comment by iJungleboy** [comment]
@enfJoao would you be willing to help us test what we're doing?

It's groundbreaking, but as such, it would benefit a lot from external feedback before we overwhelm everybody ;)

**Comment by enfJoao** [comment]
As long as it comes with a very clear set of instructions, sure.

**Comment by enfJoao** [comment]
Hey... Is this still a thing?

**Comment by iJungleboy** [comment]
yes, but still not ready. 
too much other stuff. I thought you @enfJoao dropped Oqtane again?

**Comment by enfJoao** [comment]
Until it's a bit more stable, yes. From 5.8 to 6.01 all the breaking changes broke my patience.
In a couple of weeks perhaps I'll give another go.
A nice theme would be a good incentive @iJungleboy  :)

**Comment by iJungleboy** [comment]
It will be there ;)

But first we must really redo `cre8magic` - as that is a set of building blocks for creating themes - which is too hard ATM if you want to make them great. And doing things like that is hard - so it takes time.
